#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmoothProgressBarSharp.Resource", IsApplication=false)]

namespace SmoothProgressBarSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int spbStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int spb_color = 2130771969;
			
			// aapt resource value: 0x7f010009
			public static int spb_colors = 2130771977;
			
			// aapt resource value: 0x7f010006
			public static int spb_interpolator = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int spb_mirror_mode = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int spb_reversed = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int spb_sections_count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int spb_speed = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int spb_stroke_separator_length = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int spb_stroke_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070001
			public static int spb_default_mirror_mode = 2131165185;
			
			// aapt resource value: 0x7f070000
			public static int spb_default_reversed = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int spb_default_color = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int spb_default_stroke_separator_length = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int spb_default_stroke_width = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f020000
			public static int spb_interpolator_accelerate = 2130837504;
			
			// aapt resource value: 0x7f020002
			public static int spb_interpolator_acceleratedecelerate = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int spb_interpolator_decelerate = 2130837507;
			
			// aapt resource value: 0x7f020001
			public static int spb_interpolator_linear = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public static int spb_default_interpolator = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int spb_default_sections_count = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int spb_default_speed = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public static int SmoothProgressBar = 2131230721;
			
			// aapt resource value: 0x7f080000
			public static int Theme_SmoothProgressBarDefaults = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SmoothProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public static int SmoothProgressBar_spbStyle = 0;
			
			// aapt resource value: 1
			public static int SmoothProgressBar_spb_color = 1;
			
			// aapt resource value: 9
			public static int SmoothProgressBar_spb_colors = 9;
			
			// aapt resource value: 6
			public static int SmoothProgressBar_spb_interpolator = 6;
			
			// aapt resource value: 8
			public static int SmoothProgressBar_spb_mirror_mode = 8;
			
			// aapt resource value: 7
			public static int SmoothProgressBar_spb_reversed = 7;
			
			// aapt resource value: 4
			public static int SmoothProgressBar_spb_sections_count = 4;
			
			// aapt resource value: 5
			public static int SmoothProgressBar_spb_speed = 5;
			
			// aapt resource value: 3
			public static int SmoothProgressBar_spb_stroke_separator_length = 3;
			
			// aapt resource value: 2
			public static int SmoothProgressBar_spb_stroke_width = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
