#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SmoothProgressBarSharp.Resource.Attribute.spbStyle = global::Sample.Resource.Attribute.spbStyle;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_color = global::Sample.Resource.Attribute.spb_color;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_colors = global::Sample.Resource.Attribute.spb_colors;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_mirror_mode = global::Sample.Resource.Attribute.spb_mirror_mode;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_reversed = global::Sample.Resource.Attribute.spb_reversed;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_sections_count = global::Sample.Resource.Attribute.spb_sections_count;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_speed = global::Sample.Resource.Attribute.spb_speed;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_stroke_separator_length = global::Sample.Resource.Attribute.spb_stroke_separator_length;
			global::SmoothProgressBarSharp.Resource.Attribute.spb_stroke_width = global::Sample.Resource.Attribute.spb_stroke_width;
			global::SmoothProgressBarSharp.Resource.Boolean.spb_default_mirror_mode = global::Sample.Resource.Boolean.spb_default_mirror_mode;
			global::SmoothProgressBarSharp.Resource.Boolean.spb_default_reversed = global::Sample.Resource.Boolean.spb_default_reversed;
			global::SmoothProgressBarSharp.Resource.Color.spb_default_color = global::Sample.Resource.Color.spb_default_color;
			global::SmoothProgressBarSharp.Resource.Dimension.spb_default_stroke_separator_length = global::Sample.Resource.Dimension.spb_default_stroke_separator_length;
			global::SmoothProgressBarSharp.Resource.Dimension.spb_default_stroke_width = global::Sample.Resource.Dimension.spb_default_stroke_width;
			global::SmoothProgressBarSharp.Resource.Integer.spb_default_sections_count = global::Sample.Resource.Integer.spb_default_sections_count;
			global::SmoothProgressBarSharp.Resource.Interpolator.spb_default_interpolator = global::Sample.Resource.Interpolator.spb_default_interpolator;
			global::SmoothProgressBarSharp.Resource.String.spb_default_speed = global::Sample.Resource.String.spb_default_speed;
			global::SmoothProgressBarSharp.Resource.Style.SmoothProgressBar = global::Sample.Resource.Style.SmoothProgressBar;
			global::SmoothProgressBarSharp.Resource.Style.Theme_SmoothProgressBarDefaults = global::Sample.Resource.Style.Theme_SmoothProgressBarDefaults;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar = global::Sample.Resource.Styleable.SmoothProgressBar;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_android_interpolator = global::Sample.Resource.Styleable.SmoothProgressBar_android_interpolator;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spbStyle = global::Sample.Resource.Styleable.SmoothProgressBar_spbStyle;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_color = global::Sample.Resource.Styleable.SmoothProgressBar_spb_color;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_colors = global::Sample.Resource.Styleable.SmoothProgressBar_spb_colors;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_mirror_mode = global::Sample.Resource.Styleable.SmoothProgressBar_spb_mirror_mode;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_reversed = global::Sample.Resource.Styleable.SmoothProgressBar_spb_reversed;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_sections_count = global::Sample.Resource.Styleable.SmoothProgressBar_spb_sections_count;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_speed = global::Sample.Resource.Styleable.SmoothProgressBar_spb_speed;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_stroke_separator_length = global::Sample.Resource.Styleable.SmoothProgressBar_spb_stroke_separator_length;
			global::SmoothProgressBarSharp.Resource.Styleable.SmoothProgressBar_spb_stroke_width = global::Sample.Resource.Styleable.SmoothProgressBar_spb_stroke_width;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0b0000
			public const int colors = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int gplus_colors = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int interpolators = 2131427330;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int spbStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int spb_color = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int spb_colors = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int spb_mirror_mode = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int spb_reversed = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int spb_sections_count = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int spb_speed = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int spb_stroke_separator_length = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int spb_stroke_width = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080001
			public const int spb_default_mirror_mode = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int spb_default_reversed = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int gplus_color_1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int gplus_color_2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int gplus_color_3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int gplus_color_4 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int holo_blue_dark = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int holo_green_dark = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int holo_purple_dark = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int holo_red_dark = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int holo_yellow_dark = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int spb_default_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int spb_default_stroke_separator_length = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int spb_default_stroke_width = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c000c
			public const int button = 2131492876;
			
			// aapt resource value: 0x7f0c000e
			public const int button_make = 2131492878;
			
			// aapt resource value: 0x7f0c0002
			public const int checkbox_mirror = 2131492866;
			
			// aapt resource value: 0x7f0c0001
			public const int checkbox_reversed = 2131492865;
			
			// aapt resource value: 0x7f0c000d
			public const int container = 2131492877;
			
			// aapt resource value: 0x7f0c0000
			public const int progressbar = 2131492864;
			
			// aapt resource value: 0x7f0c000f
			public const int progressbar1 = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int progressbar2 = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int progressbar3 = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int progressbar4 = 2131492882;
			
			// aapt resource value: 0x7f0c000a
			public const int seekbar_sections_count = 2131492874;
			
			// aapt resource value: 0x7f0c0008
			public const int seekbar_separator_length = 2131492872;
			
			// aapt resource value: 0x7f0c0004
			public const int seekbar_speed = 2131492868;
			
			// aapt resource value: 0x7f0c0006
			public const int seekbar_stroke_width = 2131492870;
			
			// aapt resource value: 0x7f0c000b
			public const int spinner_interpolator = 2131492875;
			
			// aapt resource value: 0x7f0c0009
			public const int textview_sections_count = 2131492873;
			
			// aapt resource value: 0x7f0c0007
			public const int textview_separator_length = 2131492871;
			
			// aapt resource value: 0x7f0c0003
			public const int textview_speed = 2131492867;
			
			// aapt resource value: 0x7f0c0005
			public const int textview_stroke_width = 2131492869;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int spb_default_sections_count = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f090000
			public const int spb_default_interpolator = 2131296256;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_custom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int spb_default_speed = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0002
			public const int AppTheme = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int GNowProgressBar = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int GPlusProgressBar = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int ProgressBar_Horizontal = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int SmoothProgressBar = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int Theme_SmoothProgressBarDefaults = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SmoothProgressBar = new int[] {
					16843073,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int SmoothProgressBar_android_interpolator = 0;
			
			// aapt resource value: 1
			public const int SmoothProgressBar_spbStyle = 1;
			
			// aapt resource value: 2
			public const int SmoothProgressBar_spb_color = 2;
			
			// aapt resource value: 9
			public const int SmoothProgressBar_spb_colors = 9;
			
			// aapt resource value: 8
			public const int SmoothProgressBar_spb_mirror_mode = 8;
			
			// aapt resource value: 7
			public const int SmoothProgressBar_spb_reversed = 7;
			
			// aapt resource value: 5
			public const int SmoothProgressBar_spb_sections_count = 5;
			
			// aapt resource value: 6
			public const int SmoothProgressBar_spb_speed = 6;
			
			// aapt resource value: 4
			public const int SmoothProgressBar_spb_stroke_separator_length = 4;
			
			// aapt resource value: 3
			public const int SmoothProgressBar_spb_stroke_width = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
